main.exe <1.in >1.out
main.exe <2.in >2.out
main.exe <3.in >3.out
main.exe <4.in >4.out
main.exe <5.in >5.out
main.exe <6.in >6.out
main.exe <7.in >7.out
main.exe <8.in >8.out
main.exe <9.in >9.out
main.exe <10.in >10.out